<?php

add_theme_support( 'title-tag' );
add_theme_support( 'html5', array( 'style', 'script' ) );

// Load translation logic without compiling .mo files
$hoasen_translations_vi = array(
    'BLOG' => 'BLOG',
    'CONTACT' => 'LIÊN HỆ',
    '01 / CONNECT' => '01 / KẾT NỐI',
    'Start smart with the Connection Board.' => 'Khởi đầu thông minh từ Connection Board.',
    'Manage grouped and color-coded connection profiles. Easily distinguish between Production (Red) and Development (Green) environments to avoid mistakes.' => 'Quản lý cấu hình kết nối được phân nhóm và gán mã màu trực quan. Dễ dàng phân biệt môi trường Production (Đỏ) và Development (Xanh) để tránh nhầm lẫn.',
    'Grouped Connections' => 'Grouped Connections',
    'Color-Coded Labels' => 'Color-Coded Labels',
    '02 / AUTOCOMPLETE' => '02 / AUTOCOMPLETE',
    'Grammar-Precise Autocomplete.' => 'Autocomplete chuẩn xác theo Ngữ pháp.',
    'Understands deep syntax and dialects of MySQL, Postgres, SQLite... Completely prevents invalid suggestions.' => 'Hiểu sâu cú pháp và các phương ngữ (Dialect) của MySQL, Postgres, SQLite... Ngăn chặn hoàn toàn các gợi ý rác không hợp lệ.',
    'Grammar-Legality' => 'Grammar-Legality',
    'Dialect-Aware' => 'Dialect-Aware',
    '03 / INTELLIGENCE' => '03 / THÔNG MINH',
    'Smart Snippets via Foreign Keys.' => 'Smart Snippet thông minh theo Khoá Ngoại.',
    'Automatically analyzes foreign key (FK) relations to suggest exact JOIN structures. Quickly fill complex ON clauses with a single keystroke.' => 'Tự động phân tích các quan hệ khoá ngoại (FK) để gợi ý cấu trúc JOIN chính xác. Điền nhanh các mệnh đề ON phức tạp chỉ bằng một phím bấm.',
    'FK-Based Join' => 'FK-Based Join',
    'Predictive Logic' => 'Predictive Logic',
    '04 / PRODUCTIVITY' => '04 / HIỆU SUẤT',
    'Minimalist High-Performance Native Workspace.' => 'Native Workspace tối giản hiệu năng cao.',
    'A pure workspace designed to maximize workflow. Visualize schemas and data instantly without redundant details.' => 'Môi trường làm việc thuần khiết được thiết kế nhằm tối đa hoá dòng chảy công việc (flow). Trực quan hoá lược đồ và dữ liệu lập tức mà không có chi tiết thừa.',
    'Focus-First UI' => 'Focus-First UI',
    'Pure Performance' => 'Pure Performance',
    '05 / DISCOVERY' => '05 / KHÁM PHÁ',
    'Instant Table Relations (Hover Relation).' => 'Truy vấn quan hệ bảng tức thời (Hover Relation).',
    'Hover over foreign key values to quickly view linked record contents without writing sub-queries or switching tabs.' => 'Di chuột lên các giá trị khoá ngoại để xem nhanh nội dung bản ghi liên kết mà không cần viết lệnh SQL phụ hay chuyển đổi tab làm việc.',
    'Instant Inspection' => 'Instant Inspection',
    'Zero Friction' => 'Zero Friction',
    '06 / CAPACITY' => '06 / SỨC MẠNH',
    'Smoothly Scroll Millions of Rows with Virtual Grid.' => 'Cuộn mượt mà hàng triệu dòng với Virtual Grid.',
    'Renders only the data visible in the viewport. Ensures ultra-smooth scrolling even with massive databases.' => 'Chỉ kết xuất những phần dữ liệu hiển thị trong khung nhìn (Viewport). Đảm bảo giao diện cuộn cực mượt mà ngay cả với cơ sở dữ liệu khổng lồ.',
    '1,000,000+ Rows' => '1,000,000+ Dòng',
    'Viewport Rendering' => 'Viewport Rendering',
    'Scroll down ↓' => 'Cuộn tiếp ↓',
    'HoaSen Table Journal' => 'HoaSen Table Journal',
    'Articles' => 'Bài viết',
    'Optimizing SQL Autocomplete by Parsing Grammar' => 'Tối ưu hóa Autocomplete SQL bằng Phân tích Ngữ pháp',
    'Published on 09/07/2026 by Engineering Team' => 'Xuất bản ngày 09/07/2026 bởi Đội ngũ kỹ thuật',
    'In traditional SQL editors, autocomplete often works by simply scanning strings. This leads to many invalid garbage suggestions at the cursor.' => 'Trong các trình soạn thảo SQL truyền thống, autocomplete thường hoạt động bằng cách quét chuỗi ký tự đơn giản. Điều này dẫn đến rất nhiều gợi ý rác không hợp lệ tại vị trí con trỏ.',
    'HoaSen Table solves this by directly integrating the parser of each DBMS. As you type, the system builds a temporary AST (Abstract Syntax Tree) to exactly determine the next valid keywords or schema objects.' => 'HoaSen Table giải quyết vấn đề này bằng cách tích hợp trực tiếp bộ phân tích cú pháp (parser) của từng hệ quản trị cơ sở dữ liệu. Khi bạn gõ, hệ thống sẽ dựng một AST (Abstract Syntax Tree) tạm thời, từ đó xác định chính xác các từ khoá hoặc đối tượng lược đồ hợp lệ tiếp theo.',
    'For example, if you just typed <code>SELECT * F</code>, the editor knows the grammar only allows a <code>FROM</code> clause here and filters out all columns or tables starting with "F".' => 'Ví dụ, nếu bạn vừa gõ <code>SELECT * F</code>, trình soạn thảo sẽ biết chắc chắn ngữ pháp chỉ cho phép mệnh đề <code>FROM</code> tại đây và lọc bỏ toàn bộ các cột hay bảng bắt đầu bằng chữ "F".',
    'Virtual Grid Mechanism: Smoothly Handling 1 Million Rows' => 'Cơ chế Virtual Grid: Xử lý 1 triệu dòng mượt mà',
    'Published on 02/07/2026 by Performance Team' => 'Xuất bản ngày 02/07/2026 bởi Đội ngũ hiệu năng',
    'Displaying millions of rows in a GUI is a major challenge for memory and CPU. A standard browser or app will freeze if it tries to render hundreds of thousands of HTML elements at once.' => 'Hiển thị hàng triệu dòng dữ liệu trên giao diện đồ họa (GUI) luôn là một thử thách lớn về bộ nhớ và CPU. Trình duyệt hoặc ứng dụng thông thường sẽ bị đơ cứng nếu cố gắng render hàng trăm ngàn thẻ HTML cùng lúc.',
    'HoaSen Table uses <b>Viewport Virtualization</b>. We only render the data rows currently visible in the user\'s viewport (around 20-30 rows). As you scroll, these elements are recycled to load new data, keeping DOM nodes to a minimum and RAM footprint to a few kilobytes.' => 'HoaSen Table sử dụng kỹ thuật <b>Viewport Virtualization</b>. Chúng tôi chỉ vẽ các dòng dữ liệu đang hiển thị trong khung nhìn của người dùng (khoảng 20-30 dòng). Khi người dùng cuộn, các phần tử này sẽ được tái sử dụng để nạp dữ liệu mới, giữ cho số lượng nút DOM luôn ở mức tối thiểu và bộ nhớ tiêu thụ chỉ khoảng vài kilobyte.',
    'Vintage UI Design: The Art of Restraint' => 'Thiết kế Giao diện Vintage: Nghệ thuật của sự Tiết chế',
    'Published on 25/06/2026 by Design Team' => 'Xuất bản ngày 25/06/2026 bởi Đội ngũ thiết kế',
    'The era of flat, monotonous SaaS interfaces has diluted brand personalities. With HoaSen Table, we return to the core values of classical print typography: elegant typefaces and deep colors.' => 'Thời đại của các giao diện SaaS phẳng lì và đơn điệu đã làm nhạt nhoà cá tính thương hiệu. Với HoaSen Table, chúng tôi quay lại giá trị cốt lõi của nghệ thuật in ấn cổ điển: kiểu chữ tinh tế và màu sắc có chiều sâu.',
    'The combination of the formal <b>Cormorant Garamond</b> serif font, the sharp contrast of ash-gray, and the deep oxblood red creates an inspiring workspace while maintaining maximum focus for complex technical tasks.' => 'Sự kết hợp giữa font chữ serif trang trọng <b>Cormorant Garamond</b>, độ tương phản sắc nét của sắc xám tro ash-gray và màu đỏ huyết dụ oxblood giúp tạo ra một giao diện làm việc đầy cảm hứng nhưng vẫn giữ được sự tập trung tối đa cho công việc kỹ thuật phức tạp.',
    'Contact HoaSen Table' => 'Liên hệ với HoaSen Table',
    'We always welcome feedback and contributions from the developer community.' => 'Chúng tôi luôn đón nhận mọi ý kiến đóng góp và phản hồi từ cộng đồng nhà phát triển.',
    'Unexecuted Query' => 'Chưa thực thi truy vấn',
    'Not loaded' => 'Chưa nạp dữ liệu',
    'Hover to discover' => 'Di chuột khám phá',
    'Hover over a foreign key value to view relations.' => 'Di chuột lên giá trị ngoại khoá để xem quan hệ.',
    'Virtual Grid Metrics' => 'Virtual Grid Metrics',
    'Rendered Rows:' => 'Dòng render:',
    'Total Rows:' => 'Tổng số:',
    'Render Time:' => 'Thời gian Render:',
    'RAM Usage:' => 'RAM tốn:',
    '60 FPS (Smooth)' => '60 FPS (Mượt mà)',
    'rows · virtual viewport' => 'dòng · virtual viewport',
    'LOAD' => 'TẢI',
    'Query Performance' => 'Hiệu năng truy vấn',
    'Execution Time' => 'Thời gian thực thi',
    'Row Count:' => 'Số dòng:',
    'Memory:' => 'Bộ nhớ:',
    'Relation Details' => 'Chi tiết liên kết',
    'Name:' => 'Tên:',
    'Status:' => 'Trạng thái:',
    'Created Date:' => 'Ngày tạo:',
    'Expected keyword' => 'Từ khoá dự kiến',
    'Smart snippet' => 'Smart snippet',
    'Data table' => 'Bảng dữ liệu',
    'Connection' => 'Kết nối',
    'Complete Syntax' => 'Cú pháp hoàn chỉnh',
    'users (Root Table)' => 'users (Bảng gốc)',
    'orders (Relation)' => 'orders (Liên kết)',
);

$hoasen_translations_ja = array(
    'BLOG' => 'ブログ',
    'CONTACT' => 'お問い合わせ',
    '01 / CONNECT' => '01 / 接続',
    'Start smart with the Connection Board.' => 'コネクションボードからスマートに始めましょう。',
    'Manage grouped and color-coded connection profiles. Easily distinguish between Production (Red) and Development (Green) environments to avoid mistakes.' => 'グループ化され色分けされた接続プロファイルを管理します。本番環境（赤）と開発環境（緑）を簡単に区別し、ミスを防ぎます。',
    'Grouped Connections' => 'グループ化された接続',
    'Color-Coded Labels' => '色分けされたラベル',
    '02 / AUTOCOMPLETE' => '02 / 自動補完',
    'Grammar-Precise Autocomplete.' => '文法に正確なオートコンプリート。',
    'Understands deep syntax and dialects of MySQL, Postgres, SQLite... Completely prevents invalid suggestions.' => 'MySQL、Postgres、SQLiteなどの深い構文と方言を理解し、無効な提案を完全に防ぎます。',
    'Grammar-Legality' => '文法適合性',
    'Dialect-Aware' => '方言対応',
    '03 / INTELLIGENCE' => '03 / インテリジェンス',
    'Smart Snippets via Foreign Keys.' => '外部キーによるスマートスニペット。',
    'Automatically analyzes foreign key (FK) relations to suggest exact JOIN structures. Quickly fill complex ON clauses with a single keystroke.' => '外部キー（FK）関係を自動分析し、正確なJOIN構造を提案します。複雑なON句をワンタッチで素早く入力できます。',
    'FK-Based Join' => 'FKベースJOIN',
    'Predictive Logic' => '予測ロジック',
    '04 / PRODUCTIVITY' => '04 / 生産性',
    'Minimalist High-Performance Native Workspace.' => 'ミニマリストで高性能なネイティブワークスペース。',
    'A pure workspace designed to maximize workflow. Visualize schemas and data instantly without redundant details.' => 'ワークフローを最大化するために設計された純粋なワークスペース。冗長な詳細なしでスキーマとデータを即座に視覚化します。',
    'Focus-First UI' => 'フォーカス優先UI',
    'Pure Performance' => '純粋なパフォーマンス',
    '05 / DISCOVERY' => '05 / 発見',
    'Instant Table Relations (Hover Relation).' => '瞬時のテーブルリレーション（ホバーリレーション）。',
    'Hover over foreign key values to quickly view linked record contents without writing sub-queries or switching tabs.' => '外部キー値にホバーするだけで、サブクエリを書いたりタブを切り替えたりせずに、リンクされたレコードの内容をすばやく表示できます。',
    'Instant Inspection' => '即時検査',
    'Zero Friction' => '摩擦ゼロ',
    '06 / CAPACITY' => '06 / キャパシティ',
    'Smoothly Scroll Millions of Rows with Virtual Grid.' => '仮想グリッドで数百万行をスムーズにスクロール。',
    'Renders only the data visible in the viewport. Ensures ultra-smooth scrolling even with massive databases.' => 'ビューポートに表示されるデータのみをレンダリングします。巨大なデータベースでも超スムーズなスクロールを保証します。',
    '1,000,000+ Rows' => '1,000,000+ 行',
    'Viewport Rendering' => 'ビューポートレンダリング',
    'Scroll down ↓' => '下にスクロール ↓',
    'HoaSen Table Journal' => 'HoaSen Table ジャーナル',
    'Articles' => '記事',
    'Optimizing SQL Autocomplete by Parsing Grammar' => '文法解析によるSQLオートコンプリートの最適化',
    'Published on 09/07/2026 by Engineering Team' => 'エンジニアリングチームによって2026年7月9日に公開',
    'In traditional SQL editors, autocomplete often works by simply scanning strings. This leads to many invalid garbage suggestions at the cursor.' => '従来のSQLエディターでは、オートコンプリートは単に文字列をスキャンすることで機能することが多く、カーソル位置に無効な不要な提案が多数表示されます。',
    'HoaSen Table solves this by directly integrating the parser of each DBMS. As you type, the system builds a temporary AST (Abstract Syntax Tree) to exactly determine the next valid keywords or schema objects.' => 'HoaSen Tableは、各DBMSのパーサーを直接統合することでこれを解決します。入力時にシステムが一時的なAST（抽象構文木）を構築し、次に有効なキーワードやスキーマオブジェクトを正確に決定します。',
    'For example, if you just typed <code>SELECT * F</code>, the editor knows the grammar only allows a <code>FROM</code> clause here and filters out all columns or tables starting with "F".' => 'たとえば、<code>SELECT * F</code>と入力した場合、エディターはここでは<code>FROM</code>句のみが文法的に許可されることを認識し、「F」で始まるすべての列やテーブルを除外します。',
    'Virtual Grid Mechanism: Smoothly Handling 1 Million Rows' => '仮想グリッドメカニズム：100万行をスムーズに処理',
    'Published on 02/07/2026 by Performance Team' => 'パフォーマンスチームによって2026年7月2日に公開',
    'Displaying millions of rows in a GUI is a major challenge for memory and CPU. A standard browser or app will freeze if it tries to render hundreds of thousands of HTML elements at once.' => 'GUIに数百万行を表示することは、メモリとCPUにとって大きな課題です。標準のブラウザやアプリは、数十万のHTML要素を一度にレンダリングしようとするとフリーズします。',
    'HoaSen Table uses <b>Viewport Virtualization</b>. We only render the data rows currently visible in the user\'s viewport (around 20-30 rows). As you scroll, these elements are recycled to load new data, keeping DOM nodes to a minimum and RAM footprint to a few kilobytes.' => 'HoaSen Tableは<b>ビューポートの仮想化</b>を使用します。ユーザーのビューポートに現在表示されているデータ行（約20〜30行）のみをレンダリングします。スクロールすると、これらの要素は新しいデータを読み込むためにリサイクルされ、DOMノードを最小限に抑え、RAMの使用量を数キロバイトに保ちます。',
    'Vintage UI Design: The Art of Restraint' => 'ヴィンテージUIデザイン：抑制の美学',
    'Published on 25/06/2026 by Design Team' => 'デザインチームによって2026年6月25日に公開',
    'The era of flat, monotonous SaaS interfaces has diluted brand personalities. With HoaSen Table, we return to the core values of classical print typography: elegant typefaces and deep colors.' => 'フラットで単調なSaaSインターフェースの時代は、ブランドの個性を薄めてしまいました。HoaSen Tableでは、古典的な活版印刷の中核的な価値観、つまりエレガントな書体と深い色合いに立ち返ります。',
    'The combination of the formal <b>Cormorant Garamond</b> serif font, the sharp contrast of ash-gray, and the deep oxblood red creates an inspiring workspace while maintaining maximum focus for complex technical tasks.' => 'フォーマルな<b>Cormorant Garamond</b>セリフフォント、アッシュグレーの鋭いコントラスト、深いオックスブラッドレッドの組み合わせは、複雑な技術的タスクに最大限の集中を維持しながら、インスピレーションを与えるワークスペースを作り出します。',
    'Contact HoaSen Table' => 'HoaSen Tableへのお問い合わせ',
    'We always welcome feedback and contributions from the developer community.' => '開発者コミュニティからのフィードバックや貢献を常に歓迎しています。',
    'Unexecuted Query' => '未実行のクエリ',
    'Not loaded' => '未読み込み',
    'Hover to discover' => 'ホバーして発見',
    'Hover over a foreign key value to view relations.' => '外部キー値にホバーして関係を表示します。',
    'Virtual Grid Metrics' => '仮想グリッドメトリクス',
    'Rendered Rows:' => 'レンダリング行数:',
    'Total Rows:' => '合計行数:',
    'Render Time:' => 'レンダリング時間:',
    'RAM Usage:' => 'RAM使用量:',
    '60 FPS (Smooth)' => '60 FPS（スムーズ）',
    'rows · virtual viewport' => '行 · 仮想ビューポート',
    'LOAD' => 'ロード',
    'Query Performance' => 'クエリパフォーマンス',
    'Execution Time' => '実行時間',
    'Row Count:' => '行数:',
    'Memory:' => 'メモリ:',
    'Relation Details' => '関係の詳細',
    'Name:' => '名前:',
    'Status:' => 'ステータス:',
    'Created Date:' => '作成日:',
    'Expected keyword' => '予期されるキーワード',
    'Smart snippet' => 'スマートスニペット',
    'Data table' => 'データテーブル',
    'Connection' => '接続',
    'Complete Syntax' => '完全な構文',
    'users (Root Table)' => 'users（ルートテーブル）',
    'orders (Relation)' => 'orders（関係）',
);

add_filter('gettext', function($translation, $text, $domain) {
    if ($domain === 'hoasen-theme') {
        global $hoasen_translations_vi, $hoasen_translations_ja;
        $loc = get_locale();
        if (strpos($loc, 'vi') === 0 && isset($hoasen_translations_vi[$text])) {
            return $hoasen_translations_vi[$text];
        }
        if (strpos($loc, 'ja') === 0 && isset($hoasen_translations_ja[$text])) {
            return $hoasen_translations_ja[$text];
        }
    }
    return $translation;
}, 10, 3);
