<?php

namespace simply_static_pro\commands\deployment;

use simply_static_pro\commands\Update_Command;


class Github extends Update_Command {

	protected $section = 'deployment';

	protected $name = 'github';

	protected $option_name = '';

	protected $description = 'Setup Github.';

	public function get_synopsis() {
		$fields = $this->get_fields();

		$synopsis = [
			[
				'type'        => 'assoc',
				'name'        => 'field',
				'description' => "You can skip the whole setup and use this for specific fields.\nAvailable fields: \n" . array_reduce( array_keys( $fields ), function ( $carry, $item ) use ( $fields ) {
						return $carry .= '- ' . \WP_CLI::colorize( '%Y' . $item . '%n' ) . ': ' . $fields[ $item ]['desc'] . "\n";
					} ),
				'optional'    => true,
				'repeating'   => false,
			],
			[
				'type'        => 'assoc',
				'name'        => 'value',
				'description' => "The field Value that will be saved. This is required if using --field",
				'optional'    => true,
				'repeating'   => false,
			]
		];

		return array_merge( $synopsis, parent::get_synopsis() ); // TODO: Change the autogenerated stub
	}

	protected function get_fields() {
		return [
			'account-type'      => [
				'field' => 'account_type',
				'name'  => 'github_account_type',
				'label' => 'Account Type',
				'desc'  => "Account Type: \n personal - Personal \n organization - Organization",
			],
			'user' => [
				'field' => 'user',
				'name'  => 'github_user',
				'label' => 'Organization or Username',
				'desc'  => "Enter the name of your organization if your account type is organization. Otherwise, your username."
			],
			'github-email'   => [
				'field' => 'github-email',
				'name'  => 'github_email',
				'label' => 'Email',
				'desc'  => "Enter your GitHub email address. This will be used to commit files to your repository"
			],
			'access-token'    => [
				'field' => 'access-token',
				'name'  => 'github_personal_access_token',
				'label' => 'Personal Access Token',
				'desc'  => "Personal Access Token from GitHub."
			],
			'repository' => [
				'field' => 'repository',
				'name'  => 'github_repository',
				'label' => 'Repository',
				'desc'  => "Enter a name for your repository (lowercase without spaces or special characters)."
			],
			'folder'    => [
				'field' => 'folder',
				'name'  => 'github_folder_path',
				'label' => 'Directory',
				'desc'  => "Enter a relative path to a folder if you want to push files under it. Example: for github.com/USER/REPOSITORY/folder1, enter folder1"
			],
			'visibility'    => [
				'field' => 'visibility',
				'name'  => 'github_repository_visibility',
				'label' => 'Visibility',
				'desc'  => "Decide if you want to make your repository public or private."
			],
			'branch'    => [
				'field' => 'branch',
				'name'  => 'github_branch',
				'label' => 'Branch',
				'desc'  => "Simply Static automatically uses \"main\" as branch. You may want to modify that for example to gh-pages. for GitHub Pages."
			],
			'webhook'    => [
				'field' => 'webhook',
				'name'  => 'github_webhook_url',
				'label' => 'Webhook URL',
				'desc'  => "Enter your Webhook URL here and Simply Static will send a POST request after all files are commited to GitHub."
			],
			'throttle'    => [
				'field' => 'throttle',
				'name'  => 'github_throttle_requests',
				'label' => 'Throttle Requests',
				'desc'  => "Enable this option if you are experiencing issues with the GitHub API rate limit. \n0 - disable \n1 - enable"
			],
		];
	}

	/**
	 * Run
	 *
	 * @param $args
	 * @param $options
	 *
	 * @return void
	 */
	public function run( $args, $options ) {
		$fields = $this->get_fields();

		if ( isset( $options['field'] ) ) {
			if ( ! isset( $fields[ $options['field'] ] ) ) {
				\WP_CLI::error( 'Not an existing field.' );

				return;
			}

			if ( ! isset( $options['value'] ) ) {
				\WP_CLI::error( 'Please provide a value for the field. Use --value to set it.' );

				return;
			}

			$this->update( $options['value'], $fields[ $options['field'] ]['name'] );
			\WP_CLI::success( 'Updated!' );

			return;
		}

		foreach ( $fields as $field ) {


			$value = $this->ask( 'Please enter value for ' . \WP_CLI::colorize( '%Y' . $field['label'] . '%n' ) . "\n" . $field['desc'] . "\nTo remove data from existing field just hit Enter.\n" );
			$this->update( $value, $field['name'] );
			\WP_CLI::success( 'Updated ' . $field['label'] . '!' );
		}
	}
}