<?php

namespace simply_static_pro\Crawler;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Simply Static The Events Calendar (TEC) Crawler class
 *
 * Detects URLs generated by The Events Calendar plugin and adds them to the export queue.
 *
 * Covered:
 * - Events archive and single event CPT (tribe_events)
 * - Event category taxonomy pages (tribe_events_cat)
 * - Calendar views (list, month, day) incl. simple pagination/ranges
 */
class The_Events_Calendar_Crawler extends \Simply_Static\Crawler\Crawler {

	/**
	 * Crawler ID.
	 * @var string
	 */
	protected $id = 'the-events-calendar';

	/**
	 * Constructor
	 */
	public function __construct() {
		$this->name = __( 'The Events Calendar URLs', 'simply-static-pro' );
		$this->description = __( 'Detects event, category, and calendar view URLs from The Events Calendar.', 'simply-static-pro' );
		$this->active_by_default = false; // Only active if TEC is present or user enables it
	}

	/**
	 * Whether The Events Calendar dependency appears active.
	 */
	public function dependency_active() : bool {
		// Check typical class/function identifiers from TEC (modern and legacy names)
		return class_exists( '\\Tribe\\Events\\Pro' )
			|| class_exists( '\\Tribe__Events__Main' )
			|| function_exists( 'tribe_get_events_link' )
			|| post_type_exists( 'tribe_events' );
	}

	/**
	 * Only active when dependency is available AND user has it enabled.
	 */
	public function is_active() {
		if ( ! $this->dependency_active() ) {
			return false;
		}
		return parent::is_active();
	}

	/**
	 * Detect URLs for The Events Calendar
	 */
	public function detect() : array {
		$urls = [];

		if ( ! $this->dependency_active() ) {
			return $urls;
		}

		$site_url = untrailingslashit( home_url() );

		// Ranges and depths (customizable via filters)
		$list_pages  = (int) apply_filters( 'ssp_tec_list_pages', 5 );
		$months_back = (int) apply_filters( 'ssp_tec_months_back', 1 );
		$months_ahead = (int) apply_filters( 'ssp_tec_months_ahead', 12 );
		$day_range_days = (int) apply_filters( 'ssp_tec_day_range_days', 14 ); // past+future window

		// 1) Events archive base
		$archive = $this->get_events_archive_url();
		if ( $archive ) {
			$urls[] = $archive;
		}

		// 2) Calendar views
		if ( $archive ) {
			// Add archive semantic endpoints
			$urls[] = trailingslashit( $archive ) . 'past';
			$urls[] = trailingslashit( $archive ) . 'today/';
			$urls[] = trailingslashit( $archive ) . 'month/';
			$urls = array_merge( $urls, $this->build_list_view_urls( $archive, $list_pages ) );
			$urls = array_merge( $urls, $this->build_month_view_urls( $archive, $months_back, $months_ahead ) );
		}

		// 3) Single events (CPT: tribe_events)
		$urls = array_merge( $urls, $this->collect_single_event_urls() );

		// 4) Event categories (tribe_events_cat)
		$urls = array_merge( $urls, $this->collect_event_category_urls( $list_pages ) );

		// Final sanitation: same-site only unique
		$urls = array_filter( array_map( 'trim', $urls ) );
		$urls = array_unique( $urls );
		$urls = array_values( array_filter( $urls, function( $url ) use ( $site_url ) {
			return is_string( $url ) && 0 === strpos( untrailingslashit( $url ), $site_url );
		} ) );

		return $urls;
	}

	/**
	 * Streamed URL discovery and queueing for large event sets.
	 */
	public function add_urls_to_queue() : int {
		if ( ! $this->dependency_active() ) {
			return 0;
		}

		$opts = \Simply_Static\Options::instance();
		$batch_size = (int) apply_filters( 'simply_static_crawler_batch_size', 100 );
		if ( $batch_size <= 0 ) { $batch_size = 100; }

		$exclude_url = '';
		if ( $opts->get( 'generate_404' ) && (int) $opts->get( 'custom_404_page' ) ) {
			$permalink = get_permalink( (int) $opts->get( 'custom_404_page' ) );
			if ( $permalink ) {
				$exclude_url = untrailingslashit( $permalink );
			}
		}

		$site_url = untrailingslashit( home_url() );
		$count = 0;
		$batch = [];
		$seen  = [];
		$flush = function() use ( &$batch, &$count ) {
			if ( empty( $batch ) ) { return; }
			\Simply_Static\Util::debug_log( sprintf( 'Processing streamed batch of %d URLs for %s crawler', count( $batch ), $this->name ) );
			foreach ( $batch as $url ) {
				$static_page = \Simply_Static\Page::query()->find_or_initialize_by( 'url', $url );
				$static_page->set_status_message( sprintf( __( 'Added by %s Crawler', 'simply-static-pro' ), $this->name ) );
				$static_page->found_on_id = 0;
				$static_page->save();
				$count++;
			}
			$batch = [];
			usleep( 100000 );
		};

		$maybe = function( $url ) use ( $site_url, $exclude_url, &$seen, &$batch, $batch_size, $flush ) {
			$url = is_string( $url ) ? trim( $url ) : '';
			if ( '' === $url ) { return; }
			if ( 0 !== strpos( untrailingslashit( $url ), $site_url ) ) { return; }
			if ( $exclude_url && 0 === strcasecmp( untrailingslashit( $url ), $exclude_url ) ) { return; }
			if ( isset( $seen[$url] ) ) { return; }
			$seen[$url] = true;
			$batch[] = $url;
			if ( count( $batch ) >= $batch_size ) { $flush(); }
		};

		// Generate in streams similar to detect()
		$archive = $this->get_events_archive_url();
		if ( $archive ) {
			$maybe( $archive );

			// Add archive semantic endpoints
			$maybe( trailingslashit( $archive ) . 'past/' );
			$maybe( trailingslashit( $archive ) . 'today/' );
			$maybe( trailingslashit( $archive ) . 'month/' );

			$list_pages  = (int) apply_filters( 'ssp_tec_list_pages', 5 );
			$months_back = (int) apply_filters( 'ssp_tec_months_back', 1 );
			$months_ahead = (int) apply_filters( 'ssp_tec_months_ahead', 12 );
			$day_range_days = (int) apply_filters( 'ssp_tec_day_range_days', 14 );

			foreach ( $this->build_list_view_urls( $archive, $list_pages ) as $u ) { $maybe( $u ); }
			foreach ( $this->build_month_view_urls( $archive, $months_back, $months_ahead ) as $u ) { $maybe( $u ); }
		}

		foreach ( $this->collect_single_event_urls( true ) as $u ) { $maybe( $u ); }
		foreach ( $this->collect_event_category_urls( (int) apply_filters( 'ssp_tec_list_pages', 5 ), true ) as $u ) { $maybe( $u ); }

		$flush();
		return $count;
	}

	// ============ Helpers ============

	private function get_events_archive_url() : string {
		$archive = '';
		if ( function_exists( 'tribe_get_events_link' ) ) {
			$archive = tribe_get_events_link();
		}
		if ( ! $archive && function_exists( 'tribe_get_events_archive_link' ) ) {
			$archive = tribe_get_events_archive_link();
		}
		if ( ! $archive ) {
			$archive = get_post_type_archive_link( 'tribe_events' );
		}
		return is_string( $archive ) ? $archive : '';
	}

	private function build_list_view_urls( string $archive, int $pages ) : array {
		$urls = [];
		// Semantic URLs only
		$base = trailingslashit( $archive ) . 'list/';
		$urls[] = $base;
		// Add pagination for list view
		for ( $i = 2; $i <= max( 1, $pages ); $i++ ) {
			$urls[] = trailingslashit( $base ) . 'page/' . $i . '/';
		}
		// Add past events semantic URL
		$urls[] = trailingslashit( $base ) . 'past/';
		return $urls;
	}

	private function build_month_view_urls( string $archive, int $back, int $ahead ) : array {
		$urls = [];
		$now = current_time( 'timestamp' );
		$start = strtotime( '-' . max( 0, $back ) . ' month', $now );
		$end   = strtotime( '+' . max( 0, $ahead ) . ' month', $now );
		$cursor = mktime( 0, 0, 0, (int) date( 'n', $start ), 1, (int) date( 'Y', $start ) );
		while ( $cursor <= $end ) {
			$ym = date( 'Y-m', $cursor );
			// Use semantic month URLs instead of query parameters
			$urls[] = trailingslashit( $archive ) . 'month/' . $ym . '/';
			$cursor = strtotime( '+1 month', $cursor );
		}
		return $urls;
	}

	private function build_day_view_urls( string $archive, int $range_days ) : array {
		$urls = [];
		$now = current_time( 'timestamp' );
		$months_ahead = (int) apply_filters( 'ssp_tec_day_months_ahead', 12 );

		if ( $months_ahead > 0 ) {
			// Generate every day from today through the next N months (inclusive)
			$start  = strtotime( 'today', $now );
			$end    = strtotime( '+' . max( 0, $months_ahead ) . ' month', $start );
			$cursor = $start;
			while ( $cursor <= $end ) {
				$ymd = date( 'Y-m-d', $cursor );
				$urls[] = trailingslashit( $archive ) . 'day/' . $ymd . '/';
				$cursor = strtotime( '+1 day', $cursor );
			}
			return $urls;
		}

		// Fallback: symmetric day range around today
		$range_days = max( 0, $range_days );
		$start = strtotime( '-' . $range_days . ' day', $now );
		$end   = strtotime( '+' . $range_days . ' day', $now );
		$cursor = $start;
		while ( $cursor <= $end ) {
			$ymd = date( 'Y-m-d', $cursor );
			// Use semantic day URLs instead of query parameters
			$urls[] = trailingslashit( $archive ) . 'day/' . $ymd . '/';
			$cursor = strtotime( '+1 day', $cursor );
		}
		return $urls;
	}

	private function collect_single_event_urls( bool $stream = false ) : array {
		$urls = [];
		$args = [
			'post_type'      => 'tribe_events',
			'post_status'    => 'publish',
			'posts_per_page' => $stream ? 100 : -1,
			'fields'         => 'ids',
		];
		$q = new \WP_Query( $args );
		if ( $q->have_posts() ) {
			foreach ( $q->posts as $pid ) {
				$perma = get_permalink( $pid );
				if ( $perma ) { $urls[] = $perma; }
			}
			wp_reset_postdata();
		}
		return $urls;
	}

	private function collect_event_category_urls( int $list_pages = 5, bool $stream = false ) : array {
		$urls = [];
		$terms = get_terms( [
			'taxonomy'   => 'tribe_events_cat',
			'hide_empty' => false,
			'fields'     => 'all',
			'number'     => $stream ? 200 : 0,
		] );
		if ( is_wp_error( $terms ) || empty( $terms ) ) {
			return $urls;
		}
		foreach ( $terms as $term ) {
			$link = get_term_link( $term );
			if ( is_wp_error( $link ) || ! $link ) { continue; }
			$urls[] = $link;
			// Semantic list view on category pages
			$base = trailingslashit( $link ) . 'list/';
			$urls[] = $base;
			for ( $i = 2; $i <= max( 1, $list_pages ); $i++ ) {
				$urls[] = trailingslashit( $base ) . 'page/' . $i . '/';
			}
			// Past events list on category page
			$urls[] = trailingslashit( $base ) . 'past/';
		}
		return $urls;
	}
}
