<?php

namespace simply_static_pro\Crawler;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Simply Static NSG SEO Generator Crawler class
 *
 * Detects URLs generated by the nsg-seo-generator plugin and adds them to the export queue.
 */
class Nsg_SEO_Generator_Crawler extends \Simply_Static\Crawler\Crawler {

	/**
	 * Crawler ID.
	 * @var string
	 */
	protected $id = 'nsg-seo-generator';

	/**
	 * Constructor
	 */
	public function __construct() {
		$this->name = __( 'SEO Generator URLs', 'simply-static-pro' );
		$this->description = __( 'Detects URLs generated by the SEO Generator plugin.', 'simply-static-pro' );
		$this->active_by_default = false; // Only active if the plugin is present or user enables it
	}

	/**
	 * Whether the dependency plugin appears active.
	 *
	 * @return bool
	 */
	public function dependency_active() : bool {
		// Minimal dependency check: NSG plugin defines the main class.
		return class_exists( '\\NSG_SEO_Generator' ) || class_exists( 'NSG_SEO_Generator' );
	}

	/**
	 * Detect URLs from NSG SEO Generator.
	 *
	 * Simplified strategy:
	 * - Optional filter allows third parties to provide URLs.
	 * - Parse NSG-related XML sitemap(s) and sitemap index to collect URLs.
	 *
	 * @return array
	 */
	public function detect() : array {
		$urls = [];

		\Simply_Static\Util::debug_log( 'NSG Crawler: starting detection (sitemaps-only)' );

		// 1) Allow third parties and the NSG plugin itself to short-circuit and provide URLs
		$provided = apply_filters( 'simply_static_nsg_seo_generator_urls', [] );
		if ( is_array( $provided ) ) {
			$urls = array_merge( $urls, $provided );
		}
		\Simply_Static\Util::debug_log( 'NSG Crawler: provided URLs via filter = ' . ( is_array( $provided ) ? count( $provided ) : 0 ) );

		// 2) Discover NSG-specific sitemap or sitemap index and extract URLs
		$home = home_url( '/' );
		$index_sitemap = trailingslashit( $home ) . 'seo_generator_sitemap_index.xml';
		$extracted_from_sitemaps = $this->collect_from_sitemaps( [ $index_sitemap ] );
		\Simply_Static\Util::debug_log( 'NSG Crawler: URLs from sitemaps = ' . count( $extracted_from_sitemaps ) );
		$urls = array_merge( $urls, $extracted_from_sitemaps );

		$site_url = untrailingslashit( home_url() );
		$urls = array_filter( array_map( 'trim', $urls ) );
		$urls = array_unique( $urls );

		// Same-site-only final filter
		$urls = array_values( array_filter( $urls, function( $url ) use ( $site_url ) {
			return is_string( $url ) && 0 === strpos( untrailingslashit( $url ), $site_url );
		} ) );

		\Simply_Static\Util::debug_log( 'NSG Crawler: total URLs detected = ' . count( $urls ) );

		return $urls;
	}

	/**
	 * Streamed URL discovery and queueing to reduce memory usage for very large datasets.
	 * Simplified to rely on NSG XML sitemaps (and optional filter-provided URLs).
	 *
	 * @return int Number of URLs added
	 */
	public function add_urls_to_queue() : int {
		$opts = \Simply_Static\Options::instance();
		$batch_size = (int) apply_filters( 'simply_static_crawler_batch_size', 100 );
		if ( $batch_size <= 0 ) { $batch_size = 100; }

		// Determine excluded URL if a custom 404 page is selected
		$exclude_url = '';
		if ( $opts->get( 'generate_404' ) && (int) $opts->get( 'custom_404_page' ) ) {
			$permalink = get_permalink( (int) $opts->get( 'custom_404_page' ) );
			if ( $permalink ) {
				$exclude_url = untrailingslashit( $permalink );
			}
		}

		$site_url = untrailingslashit( home_url() );
		$count = 0;
		$batch = [];
		$batch_seen = [];

		$flush = function() use ( &$batch, &$count, &$batch_seen ) {
			if ( empty( $batch ) ) { return; }
			\Simply_Static\Util::debug_log( sprintf( 'Processing streamed batch of %d URLs for %s crawler', count( $batch ), $this->name ) );
			foreach ( $batch as $url ) {
				$static_page = \Simply_Static\Page::query()->find_or_initialize_by( 'url', $url );
				$static_page->set_status_message( sprintf( __( 'Added by %s Crawler', 'simply-static-pro' ), $this->name ) );
				$static_page->found_on_id = 0;
				$static_page->save();
				$count++;
			}
			$batch = [];
			$batch_seen = [];
			usleep( 100000 ); // yield ~0.1s
		};

		$maybe_queue = function( $url ) use ( $site_url, $exclude_url, &$batch, &$batch_seen, $batch_size, $flush ) {
			$url = is_string( $url ) ? trim( $url ) : '';
			if ( '' === $url ) { return; }
			// Same-site only
			if ( 0 !== strpos( untrailingslashit( $url ), $site_url ) ) { return; }
			// Exclude custom 404 page
			if ( $exclude_url && 0 === strcasecmp( untrailingslashit( $url ), $exclude_url ) ) { return; }
			// Avoid duplicates within current batch
			if ( isset( $batch_seen[ $url ] ) ) { return; }
			$batch_seen[ $url ] = true;
			$batch[] = $url;
			if ( count( $batch ) >= $batch_size ) {
				$flush();
			}
		};

		\Simply_Static\Util::debug_log( 'NSG Crawler: streaming detection start (sitemaps-only)' );

		// 1) Provided URLs via filter
		$provided = apply_filters( 'simply_static_nsg_seo_generator_urls', [] );
		if ( is_array( $provided ) ) {
			foreach ( $provided as $u ) { $maybe_queue( $u ); }
		}

		// 2) Sitemaps (including sitemap indexes) streamed
		$home = home_url( '/' );
		$index_sitemap = trailingslashit( $home ) . 'seo_generator_sitemap_index.xml';
		$visited = [];
		$this->crawl_sitemap_url_stream( $index_sitemap, $visited, function( $loc ) use ( $maybe_queue ) { $maybe_queue( $loc ); } );

		// Final flush
		$flush();

		\Simply_Static\Util::debug_log( 'NSG Crawler: streaming detection finished, total queued so far: ' . $count );
		return $count;
	}

	/**
	 * Stream a sitemap or sitemap index and invoke a callback for each URL.
	 * @param string   $url
	 * @param string[] $visited
	 * @param callable $on_url function( string $url ) : void
	 * @return void
	 */
	private function crawl_sitemap_url_stream( $url, array &$visited, callable $on_url ) : void {
		$url = (string) $url;
		if ( '' === $url ) { return; }
		if ( isset( $visited[ $url ] ) ) { return; }
		$visited[ $url ] = true;

		$response = wp_remote_get( $url, [ 'timeout' => 8 ] );
		if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
			return;
		}
		$body = (string) wp_remote_retrieve_body( $response );
		if ( '' === $body ) { return; }

		$lower = strtolower( $body );
		$locs = $this->extract_locs_from_xml( $body );
		if ( false !== strpos( $lower, '<sitemapindex' ) ) {
			foreach ( $locs as $child ) {
				if ( preg_match( '#\.xml($|\?)#i', $child ) ) {
					$this->crawl_sitemap_url_stream( $child, $visited, $on_url );
				}
			}
			return;
		}
		foreach ( $locs as $loc ) { $on_url( $loc ); }
	}


	/**
	 * Collect URLs from a list of sitemap URLs. Supports sitemap indexes recursively.
	 * @param array $sitemap_urls
	 * @return array
	 */
	private function collect_from_sitemaps( array $sitemap_urls ) : array {
		$visited = [];
		$all = [];
		foreach ( array_unique( $sitemap_urls ) as $url ) {
			$urls = $this->crawl_sitemap_url( $url, $visited );
			if ( ! empty( $urls ) ) {
				$all = array_merge( $all, $urls );
			}
		}
		return array_values( array_unique( $all ) );
	}

	/**
	 * Crawl a sitemap or sitemap index URL and return contained page URLs.
	 * Uses recursion for indexes and guards against cycles via $visited.
	 * @param string $url
	 * @param array  $visited
	 * @return array
	 */
	private function crawl_sitemap_url( $url, array &$visited ) : array {
		$url = (string) $url;
		if ( '' === $url ) { return []; }
		if ( isset( $visited[ $url ] ) ) { return []; }
		$visited[ $url ] = true;

		$response = wp_remote_get( $url, [ 'timeout' => 8 ] );
		if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
			return [];
		}
		$body = (string) wp_remote_retrieve_body( $response );
		if ( '' === $body ) { return []; }

		$lower = strtolower( $body );
		$locs = $this->extract_locs_from_xml( $body );

		// If this is a sitemap index, recurse into its children.
		if ( false !== strpos( $lower, '<sitemapindex' ) ) {
			$all = [];
			foreach ( $locs as $child ) {
				if ( preg_match( '#\.xml($|\?)#i', $child ) ) {
					$all = array_merge( $all, $this->crawl_sitemap_url( $child, $visited ) );
				}
			}
			return $all;
		}

		// Otherwise, assume this is a normal sitemap with <urlset> and the locs are page URLs
		return $locs;
	}

	/**
	 * Extract generic <loc> entries from XML (both sitemap and sitemap index)
	 * @param string $xml
	 * @return array
	 */
	private function extract_locs_from_xml( $xml ) : array {
		$found = [];
		if ( empty( $xml ) || ! is_string( $xml ) ) {
			return $found;
		}
		if ( preg_match_all( '#<loc>\s*([^<\s]+)\s*</loc>#i', $xml, $m ) ) {
			$found = $m[1];
		}
		return $found;
	}


}
